import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useCallback} from "react";
import {animated, easings, useChain, useSpring, useSpringRef} from 'react-spring';

const Home: NextPage = () => {
  const stopServer = useCallback(() => {
    // @ts-ignore
    fetch(process.env.NEXT_PUBLIC_LAMBDA_URL)
  }, [])

  const text1Ref = useSpringRef()
  const text2Ref = useSpringRef()
  const text3Ref = useSpringRef()

  const props1 = useSpring({
    to: { opacity: 0 },
    from: { opacity: 1 },
    delay: 3000,
    config: {
      duration: 1000,
      easing: easings.easeInOutQuart
    },
    ref: text1Ref
  })

  const props2 = useSpring({
    to: [{ opacity: 1 }, { opacity: 0}],
    from: { opacity: 0 },
    delay: 1000,
    config: {
      duration: 2000,
      easing: easings.easeInOutQuart
    },
    ref: text2Ref
  })

  const props3 = useSpring({
    to: [{ opacity: 1 }],
    from: { opacity: 0 },
    delay: 1000,
    config: {
      duration: 1000,
      easing: easings.easeInOutQuart
    },
    onStart: () => {
      stopServer()
      console.log('stop!!!')
      setTimeout(() => {
        location.href = 'https://marriage.cheap-lab.tech'
      }, 15000)
    },
    ref: text3Ref
  })

  useChain([text1Ref, text2Ref, text3Ref])

  return (
    <div className={styles.container}>
      <Head>
        <title>結婚おめでとうメッセージ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.textBox}>
          <animated.p style={props1} className={styles.message}>梶野<br/>結婚おめでとう!!</animated.p>
          <animated.p style={props2} className={styles.message}>末長くお幸せに🎉</animated.p>
          <animated.p style={props3} className={styles.smallMessage}>このメッセージは10秒後に<br/>自動的に消滅する</animated.p>
        </div>
      </main>
    </div>
  )
}

export default Home
